# Generated by Django 5.0.6 on 2024-05-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='last_name',
            new_name='second_name',
        ),
    ]
